
###

POST http://localhost:3000/users/signin 
Content-Type: application/json

{
"name": "Tanmay", 
"username": "tanmay", 
"password": "Password234"
}

###
POST http://localhost:3000/users/login 
Content-Type: application/json

{
"name": "Tanmay", 
"username": "tanmay", 
"password": "Password234"
}